version: '3.4'

services:
  membersrvc:
    image: hyperledger/fabric-membersrvc:x86_64-0.6.1-preview
    hostname: membersrvc
    ports:
      - "7054:7054"
    environment:
      - CORE_LOGGING_SERVER=debug
      - MEMBERSRVC_CA_ACA_ENABLED=true
      - MEMBERSRVC_LOGGING_LEVEL=DEBUG
  #  volumes:
  #    - ./blockchain/membersrvc.yaml:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc/membersrvc.0.6.yaml
    command: membersrvc

  vp0:
    image: hyperledger/fabric-peer:x86_64-0.6.1-preview
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "sleep 5; peer node start"
    hostname: vp0
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
      - CORE_SECURITY_ENABLED=true
      - CORE_PEER_ID=vp0
      - CORE_PEER_DISCOVERY_PERIOD=1s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=1s
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    links:
      - membersrvc

  mongo_data:  
    image: mongo:3.4
    container_name: mongo_data
    command: bin/true
    links:
      - membersrvc

  mongo:
    image: mongo:3.4
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: on-failure
    command: --smallfiles --rest
    links:
      - membersrvc

  graphql:
    container_name: graphql
    env_file: .env
    image: graphql
    restart: on-failure
    links:
      - membersrvc
    working_dir: /usr/app
    command: nodemon ./src/graphql/index.js --exec babel-node
    depends_on:
      - vp0
      - membersrvc
      - mongo
    volumes:
      - ./src:/usr/app/src
    ports:
      - "5000:5000"
volumes:
  mongo_data:
  # blockchain-explorer
#  explorer:
#    extends:
#      file: explorer.yml
#      service: explorer
#    hostname: explorer
#    environment:
#      - HYP_REST_ENDPOINT=http://vp0:7050
#    ports:
#      - "8080:8080"

#explorer:
#  extends:
#    file: explorer.yml
#    service: explorer
#  hostname: explorer
#  environment:
#    - HYP_REST_ENDPOINT=http://vp0:7050
#  ports:
#    - "8080:8080"

#vp1:
#  extends:
#    file: compose-defaults.yml
#    service: vp
#  environment:
#    - CORE_PEER_ID=vp1
#    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
#    - CORE_SECURITY_ENROLLID=test_vp1
#    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
#  links:
#    - vp0
#    - membersrvc
#
#    activate for testing in a simulated bluemix blockchain service environment
#vp2:
#  extends:
#    file: compose-defaults.yml
#    service: vp
#  environment:
#    - CORE_PEER_ID=vp2
#    - CORE_PEER_DISCOVERY_ROOTNODE=vp1:7051
#    - CORE_SECURITY_ENROLLID=test_vp2
#    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
#  links:
#    - vp1
#    - membersrvc
#
#vp3:
#  extends:
#    file: compose-defaults.yml
#    service: vp
#  environment:
#    - CORE_PEER_ID=vp3
#    - CORE_PEER_DISCOVERY_ROOTNODE=vp2:7051
#    - CORE_SECURITY_ENROLLID=test_vp3
#    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
#  links:
#    - vp2
#    - membersrvc
